### ISSUE TITLE
cannot handle numeric identities when they > max integer value

### ISSUE THREAD

**Issue by chengen1213** [DapperLib/Dapper.Contrib#113]
System.OverflowException: Value was either too large or too small for an Int32.
at System.Decimal.ToInt32(Decimal d)
at System.Decimal.op_Explicit(Decimal value)
at SqlCeServerAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) in /_/Dapper.Contrib/SqlMapperExtensions.cs:line 884
at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in /_/Dapper.Contrib/SqlMapperExtensions.cs:line 377

var id = (int)r[0].id;

in \SqlMapperExtensions.cs

line 884 - cannot handle numeric identities when they > max integer value

**Comment by emilsteen** [comment]
This has been known since 2016 and is being considered since 2017 for version 3.
[Value was either too large or too small for an Int32](https://github.com/DapperLib/Dapper/issues/688).

So it is probably not going to be solved soon. I'm currently looking for a work-around myself.
